### ISSUE TITLE
CoruñaJUG 7: Jenkins con Eloy

### ISSUE THREAD

**Issue by antonmry** [CorunaJUG/corunajug.github.io#15]
- [x] Confirmar temática e ponentes: Jenkins con @eloycoto
- [x] Confirmar local: Agora
- [x] Confirmar calendar
- [x] Cartel: 
- [x] Crear en meetup: https://www.meetup.com/CorunaJUG/events/258729037/
- [x] Publicar en Slack
- [x] Publicar en Twitter e Linkedin
- [ ] ~~Enviar a empresas~~
- [ ] ~~Envío a universidades e FPs~~
- [x] Preparar kahoot
- [x] Mandar correo recordatorio (1 día antes)
- [x] Re anunciar en twitter e slack (1 día antes)
- [x] Avisar no bar
- [x] Facer o meetup
- [x] Subir slides a Meetup
- [ ] Subir fotos a Meetup
- [x] Enviar la licencia al ganador
- [x] Lanzar o seguinte meetup

**Comment by ismael-hasan** [comment]
@antonmry , normalmente te encargas tú de todo - posiblemente por inactividad mía xD. Para evitar que solapemos esfuerzos, de qué puntos quieres que me encargue? Puede que te pida feedback sobre algún procedimiento, pero así aprendo para la próxima

**Comment by antonmry** [comment]
@ismael-hasan gracias por el ofrecimiento!

¿Cuales te apetecen más?. Algo en lo que siempre flojeo es en subir las fotos de Twitter a Meetup una vez pasado. Por ejemplo, estas:

https://github.com/CorunaJUG/corunajug.github.io/issues/13
https://github.com/CorunaJUG/corunajug.github.io/issues/12

También me suele costar el tema de los anuncios en RRSS (Twitter/Linkedin), es de esas cosas que siempre llevo con retraso

Sería guay si pudieras conectarte al Slack de corunadevelopers, en Vigo tenemos un grupo privado y funciona muy bien: https://join.slack.com/t/corunadevelopers/shared_invite/enQtMzAxMzU4MzMwMDMyLThkNWYwMzMzODUzMmE0MDE0MGFhZjIxM2U5MzdkYjhlNTM3ZDZhYjliNTk4NWRhYzYwMzI0MjRlZjUyN2JiN2U
